### ISSUE TITLE
dts-gen

### ISSUE THREAD

**Issue by StreetStrider** [Rich-Harris/dts-buddy#5]
I remember some people working on this. Check google, `dts-generator`, `dts-bundle-generator`, `dts-gen` is it what you're looking for?

**Comment by Rich-Harris** [comment]
Thanks but none of these are equivalent. `dts-gen` is solving a completely different problem, `dts-generator` doesn't do sourcemaps, and `dts-bundle-generator` operates on a single entry point

**Comment by timocov** [comment]
> and dts-bundle-generator operates on a single entry point

Technically it works on multiple entries too, but you'd probably mean here that [it doesn't extract common chunks out of entries](https://github.com/timocov/dts-bundle-generator/issues/69) (and sourcemaps problem is applicable too).
