### ISSUE TITLE
Invalid types distributed in 0.2.0+

### ISSUE THREAD

**Issue by benmccann** [Rich-Harris/dts-buddy#52]
This is happening in 0.2.3 and has been happening since 0.2.0

```
node_modules/.pnpm/dts-buddy@0.2.3/node_modules/dts-buddy/types/index.d.ts(2,16): error TS1003: Identifier expected.
```

![Screenshot from 2023-08-28 10-56-28](https://github.com/Rich-Harris/dts-buddy/assets/322311/af44497d-31fd-4983-8ef3-6b1d3822563c)

**Comment by Rich-Harris** [comment]
FFS

**Comment by Rich-Harris** [comment]
Fixed in https://github.com/Rich-Harris/dts-buddy/pull/54 but the default import is problematic — it may fail unless `esModuleInterop` is set. I don't know if that extends to dependencies or not. What a clusterfuck this entire ecosystem is
