### ISSUE TITLE
Support TypeScript 5.3

### ISSUE THREAD

**Issue by benmccann** [Rich-Harris/dts-buddy#66]
From the SvelteKit `version-2` branch:
```
packages/kit
└─┬ dts-buddy 0.4.0
  └── ✕ unmet peer typescript@">=5.0.4 <5.3": found 5.3.2
```

**Comment by dominikg** [comment]
ts 5.3 doesn't parse jsdoc completely anymore by default, we might have to set a new option here <https://github.com/Rich-Harris/dts-buddy/blob/main/src/index.js#L79>  see https://github.com/microsoft/TypeScript/pull/55739
