### ISSUE TITLE
Rollup Plugin DTS

### ISSUE THREAD

**Issue by KonnorRogers** [Rich-Harris/dts-buddy#7]
Would using Rollup be an option?

> Unfortunately, I couldn't find a tool for generating .d.ts bundles, at least not one that worked. dts-buddy aims to fill the gap.

 https://www.npmjs.com/package/rollup-plugin-dts

this is used by [tsup](https://github.com/egoist/tsup) internally for generating bundled `.d.ts`

not here to tell you what to do, but I've hit this brick wall before and solved it this way.

**Comment by Rich-Harris** [comment]
tried it, it failed on fairly simple input with a 'syntax not yet implemented' error. IIRC it also doesn't handle subpackages

**Comment by KonnorRogers** [comment]
@Rich-Harris 👍 

Looking forward to more from this tool tbh. It's a huge pain point and I love authoring libraries in JSDOC.
